name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Build and Test Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'maven'

      - name: Build and Test Backend
        working-directory: ./doc-arts-backend
        run: mvn clean verify org.jacoco:jacoco-maven-plugin:report

      - name: Check Backend Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./doc-arts-backend/target/site/jacoco/jacoco.xml
          flags: backend

  frontend:
    name: Build and Test Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.8.0'
          cache: 'npm'
          cache-dependency-path: doc-arts-ui/package-lock.json

      - name: Install Dependencies
        working-directory: ./doc-arts-ui
        run: npm ci

      - name: Run Tests with Coverage
        working-directory: ./doc-arts-ui
        run: npm test -- --coverage

      - name: Check Frontend Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./doc-arts-ui/coverage
          flags: frontend

      - name: Build Frontend
        working-directory: ./doc-arts-ui
        run: npm run build
