# File: .github/workflows/ci-pipeline.yml

name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Build, Test, and Check Coverage for Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for comparison

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'maven'

      - name: Build and Test Backend with Coverage
        working-directory: ./doc-arts-backend
        run: mvn clean verify

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: backend-coverage-report
          path: ./doc-arts-backend/target/site/jacoco/jacoco.xml

  frontend:
    name: Build, Test, and Check Coverage for Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for comparison

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.8.0'
          cache: 'npm'
          cache-dependency-path: doc-arts-ui/package-lock.json

      - name: Install Dependencies
        working-directory: ./doc-arts-ui
        run: npm ci

      - name: Run Tests with Coverage
        working-directory: ./doc-arts-ui
        run: npm test -- --coverage

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: frontend-coverage-report
          path: ./doc-arts-ui/coverage/clover.xml

  coverage_check:
    name: Compare Coverage and Fail on Decrease
    runs-on: ubuntu-latest
    needs: [backend, frontend]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download Backend Coverage Report
        uses: actions/download-artifact@v3
        with:
          name: backend-coverage-report
          path: ./coverage-reports/backend

      - name: Download Frontend Coverage Report
        uses: actions/download-artifact@v3
        with:
          name: frontend-coverage-report
          path: ./coverage-reports/frontend

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Node.js version compatible with dorny/coverage-check

      - name: Run Coverage Check
        uses: dorny/coverage-check@v2
        with:
          fail-on-coverage-decrease: true
          files: |
            backend:
              base: ${{ github.event.pull_request.base.sha }}:doc-arts-backend/target/site/jacoco/jacoco.xml
              head: ./coverage-reports/backend/jacoco.xml
              path: doc-arts-backend/src/main/java
              format: jacoco
            frontend:
              base: ${{ github.event.pull_request.base.sha }}:doc-arts-ui/coverage/clover.xml
              head: ./coverage-reports/frontend/clover.xml
              path: doc-arts-ui/src
              format: clover
